dist: trusty
sudo: required
language: python
cache:
  pip: true
  directories:
    - $HOME/FFmpeg
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
env:
  - FFMPEG_VERSION=2.2  # first version with ebur128 filter, and peak detection
  - FFMPEG_VERSION=2.3
  - FFMPEG_VERSION=2.4
  - FFMPEG_VERSION=2.5
  - FFMPEG_VERSION=2.6
  - FFMPEG_VERSION=2.7
  - FFMPEG_VERSION=2.8
  - FFMPEG_VERSION=3.0
  - FFMPEG_VERSION=3.1
  - FFMPEG_VERSION=3.2
  - FFMPEG_VERSION=master
matrix:
  allow_failures:
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "3.7-dev"
    - env: FFMPEG_VERSION=master
  fast_finish: true
before_install:
  - "sudo ./ci/install-ffmpeg $FFMPEG_VERSION"
  - "pip install -U pip"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
script:
  - "coverage run --source=amg setup.py test"
after_success:
  - "coveralls"
before_deploy:
  - "sudo apt-get -V install pandoc"
  - "pip install pypandoc"
  - "pip install restructuredtext_lint && t=$(mktemp --suffix=.rst) && pandoc README.md -o $t && rst-lint $t"
deploy:
  provider: pypi
  user: desbma
  password:
    secure: "lg0QFDZYapb3ymzV4eX7cE28Rna9J5OZOkfDTLI816oRWLOUyFMFtLRgwte0J8CbGju/fBIGEtHS+ete7Y4GKCjFiXIfTWe059vzaoByWlT7SigCs41DfWVbgovwp+8ECdjqA+rfzzBZqJxMMf5ol8ajWorV6fkVatkHGQC8BP/ykgpCC8fOwd9ok6zVZkDJ5ZLNU1TUIywuz3ENnrvdnxuKm59xZH/fZWHr5eWb1t8tGrce8rwfdOqJbTWW2+OiqCyh1a/iHUIuRhPOFIcZWcVmAs/+O7yuXee+3pbkRXZd/Wp+BLLgTvJKYKT+BV4m798VgL7iLJPqQhvyCibqHHx+whsY5xSyFKMAn5hDUOLyw9Yn/WDekqj5lg2qr8xfMtS7+6SmCCJ9QkRufU13vgzFdZXMSh1V72mNb1qYiWn87E0EUzSgdPU0alOaddCuQIwbbewoIXvK33PMkxUilk3yUnImzNRMXw9VyNR/QsCWysAKbkAt4A8me6qi4fMId1Fkrhq0Wk4ftw1eWAQaqWhHH5m2xgUo05v1OyL9QGblb2y3/QpCVPlDCygILJDbqtAvdKJJDHdtvCabTzllTvr+J6FS4tbxzydMi0L/zY0q9n2H8f1QpeoXDK6sMymIMtRtUw2EyYj/Ec+x+fr/5VCxIz0YTwDGd8mM05RaCOE="
  on:
    tags: true
    branch: master
notifications:
  email:
    recipients:
      - secure: "UpOIgHxqo6pWbx2WJEpOYCo9Meel2E5NgdffXe0L2cYHH0kOsEtIUrjKE+2OOQ0H7L1QK84jwctAdKfuNc8Q6uY0LbbcB0lKUb100ZyXeyt7G75b0pqFTJ8DAMI0oH7K6Ek+cTGH0mC7WVVLnHsMF4EwHs3yEnyE6x3smniM+UwgOxboE870eFQ7g56wc7YkVJJlhQGjHAvZ5tMeCSt5gHGjGwg/32lHL3GVrB9opDq9bkRKbKpcOwL7krjICTxAkA1N0O20dqBWSNL4gJ09v4ngWUUibbkBvpxlrgWVXYrPLidPJ9xP8dwgheHxDUO0ZitYDyzjJQ/J1KG0AOhmBbQTNtAoGtsY5c9TMwE1VRFxQFx2gAzlLMZOxdITpECt7UPcLImUgTa/nOz1f7KIYTOdiVD3tj/skzLsCoXQtgnr3H/JIt3ZP0EgMzTC0Qqq18B3adae0cFTt9S3W3sqJtKq0O6yOnGdloWyBB8IVcHiNQ8T4gkraFjBPE5LEDifFEwXKUqPieiQNeATE/aezIN1+RWuPwvijU1Iqt2cfYT8sIV66J9pMjiP5UxKAEc57pS/WPZQXlwCwwctGDfYd7vkqCtFa5OvKEh3A33se+6fBpkhPbBkx2NawtKPuu/rb2VLG6LEZgQiT1g0MFNEoQvnKYL8wgL+nG+cGvo5JYg="
    on_success: always
    on_failure: always
